version: '3'

services:
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    container_name: shop_management_order_api
    environment:
      - DATABASE_URL=postgresql://postgres:lelamtuan@shop-management-instance.c7cs0m28m6l4.ap-southeast-2.rds.amazonaws.com:5432/shop_management_order?schema=public
      - AMQP_ORDER_URL=amqps://lyhwedur:p0xoHlnGxtV0Z60p5mKpizY0Ow3QEZ36@armadillo.rmq.cloudamqp.com/lyhwedur
    restart: 'always'
