version: '3'

services:
  backend:
    image: letuan45/shop-management-order-backend
    container_name: shop_management_order_api
    environment:
      - DATABASE_URL=postgresql://postgres:lelamtuan@shop-management-instance.c7cs0m28m6l4.ap-southeast-2.rds.amazonaws.com:5432/shop_management_order?schema=public
      - AMQP_ORDER_URL=amqps://mlkmitde:gFMA_PMu_GnbzCGxrlmr2nGleqMzMSTm@octopus.rmq3.cloudamqp.com/mlkmitde
    restart: 'always'
